version: '2'
services:
  app:
    build:
      context: .
      args:
        rails_env: development
    network_mode: bridge
    volumes:
      - .:/code
    environment:
      - DATABASE_HOST=pg
      - DATABASE_USERNAME=postgres
    ports:
      - 3000:3000
    links:
      - pg
      - redis
  pg:
    image: postgis/postgis:12-3.0
    network_mode: bridge
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    network_mode: bridge
    volumes:
      - redis-data:/data
volumes:
  pg-data: {}
  redis-data: {}
